/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e225709;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

class PlayerTest {
    @Test void handCheckTest() {
        Player demoPlayer = new Player("デモプレイヤー");
        //５カード判定 (hand=6) になるかのテスト
        List<Integer> suitCount = new ArrayList<>(Arrays.asList(5,0,0,0));
        demoPlayer.handCheck(suitCount,demoPlayer);
        assertEquals(6,demoPlayer.getHand());

        //４カード判定 (hand=5) になるかのテスト
        List<Integer> suitCount2 = new ArrayList<>(Arrays.asList(4,1,0,0));
        demoPlayer.handCheck(suitCount2,demoPlayer);
        assertEquals(5,demoPlayer.getHand());

        //フルハウス判定（hand=4) になるかのテスト
        List<Integer> suitCount3 = new ArrayList<>(Arrays.asList(3,2,0,0));
        demoPlayer.handCheck(suitCount3,demoPlayer);
        assertEquals(4,demoPlayer.getHand());

        //３カード判定（hand=3) になるかのテスト
        List<Integer> suitCount4 = new ArrayList<>(Arrays.asList(3,1,1,0));
        demoPlayer.handCheck(suitCount4,demoPlayer);
        assertEquals(3,demoPlayer.getHand());

        //２ペア判定 (hand=2)　になるかのテスト
        List<Integer> suitCount5 = new ArrayList<>(Arrays.asList(2,2,1,0));
        demoPlayer.handCheck(suitCount5,demoPlayer);
        assertEquals(2,demoPlayer.getHand());

        //１ペア判定 (hand=1) になるかのテスト
        List<Integer> suitCount6 = new ArrayList<>(Arrays.asList(2,1,1,1));
        demoPlayer.handCheck(suitCount6,demoPlayer);
        assertEquals(1,demoPlayer.getHand());
    }
}
